// <auto-generated />
namespace Trogsoft.Project.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_ModuleContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_ModuleContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181431525_User_ModuleContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
