// <auto-generated />
namespace Trogsoft.Project.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IterationMissingPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IterationMissingPK));
        
        string IMigrationMetadata.Id
        {
            get { return "201802182228213_IterationMissingPK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
